= Biodiversity Data Repository Messaging Ontology

This respository contains the human- and machine-readable specification and documentation of an ontology that describes the sorts of messages that may be sent to the https://www.dcceew.gov.au/[Department of Climate Change, Energy, the Environment and Water]'s _Biodiversity Data Repository_ (BDR).

This ontology should be used to echanges https://linked.data.gov.au/def/abis[ABIS] information with the BDR, so see the https://linked.data.gov.au/def/abis/spec[ABIS Specification] for full details about message content.

This ontology is rendered online at the persistent identifier location of:

* *https://linked.data.gov.au/def/bdr-msg*

== License

The content of this repository is licensed for reuse using the https://creativecommons.org/licenses/by/4.0/[Creative Commons BY 4.0] license, as per Australian Government expectations. A copy of the license deed is in the file LICENSE.

== Contact

ABIS is owned by the Australian Biodiversity Governance Group (AusBIGG) and managed by the ABIS working group with asstance from the https://www.dcceew.gov.au/[Department of Climate Change, Energy, the Environment and Water] and https://www.tern.org.au[TERN].

For enquiries, please contact:  

_ABIS WG Co-chairs_:  +
**Siddeswara Guru**  +
<s.guru@uq.edu.au>  

**Kheeran Dharmawarden a** +
<kheeran.dharmawardena@dcceew.gov.au>

_Technical contact_: +
**Nicholas Car** +
_Data Architect_ +
<nick@kurrawong.ai>
